# -*- coding: utf-8 -*-
"""cleaner-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17cAsKDOAGR6es2JJOunnNqWlhr-VofoC
"""

import random

class State:
   #  the state of the cleaning environment

    def __init__(self, tiles={(0,0):True, (0,1):True, (1,0):True}, agents={1:(0,0)}):
        """
        tiles (dict) has tile cordinations as key and their dirtiness as  a boolean value for example {(0,0):True, (0,1): True}
        agents (dict) has agent number as key and their location as value for example {1:(0,0), 2:(1,0)}
        """
        self.tiles = tiles
        self.agents = agents


    def clean_update(self, agent_number):
        # this function activates when agent does "clean" action
        agent_loc = self.agents[agent_number]
        print("clean_update_", agent_loc)
        self.tiles[agent_loc] = False

    def make_room_dirty(self):
        clean_rooms = [room for room, state in self.tiles.items() if not state]

        if clean_rooms:  # Check if there are any 'False' rooms
            # Randomly select one of the 'False' rooms
            room_to_change = random.choice(false_rooms)

            # Generate a random number between 0 and 1
            if random.random() < 0.2:  # 20% probability
                self.tiles[room_to_change] = True  # Change to True / dirty


    def movement_update(self, agent_number, direction):
        # this function activates when agent does any of movement actions
        agent_loc = self.agents[agent_number]
        print("mvmnt_update_", agent_loc)
        i = agent_loc[0]
        j = agent_loc[1]

        if (direction == "up"):
          if ((i+1,j) in self.tiles):
            self.agents[agent_number] = (i+1, j)

        elif (direction == "down"):
          if ((i-1,j) in self.tiles):
            self.agents[agent_number] = (i-1, j)

        elif (direction == "left"):
          if ((i,j-1) in self.tiles):
            self.agents[agent_number] = (i, j-1)

        elif (direction == "right"):
          if ((i,j+1) in self.tiles):
            self.agents[agent_number] = (i, j+1)


    def get_percept_for_agent(self, agent_number):
      #percept is a dictionary. for example {"loc":(1,1), "dirty":True}
      agent_loc = self.agents[agent_number]
      print("send_percept to agent at ", agent_loc)
      isdirty = self.tiles[agent_loc]
      percept = {"loc": agent_loc, "dirty": isdirty}
      return percept



class Action:
    """Defines actions that a specific cleaning agent can perform."""

    def __init__(self, agent_number):
        self.agent_number = agent_number

    def move(self, env, direction):
        env.move_agent(self.agent_number, direction)

    def clean(self, env):
        """Cleans the current position of the agent."""
        env.clean_room(self.agent_number)

    def sleep(self)

class env:
    def __init__(self, state, loc_observability, dirt_observability, move_determinism, suck_determinism, static):
        self.state = state
        self.loc_observability = loc_observability
        self.dirt_observability = dirt_observability
        self.move_determinism = move_determinism
        self.suck_determinism = suck_determinism,
        self.static = static


    def clean_room(self, agent_number):
      if(self.suck_determinism==False):
          if random.random() < 0.2:  # 20% probability to not suck despite order of suck
            print(f"Agent {agent_number} intended to suck, but didn't.")
            return
      self.state.clean_update(agent_number)


    def move_agent(self, agent_number, direction):
      if(self.move_determinism==False):
          if random.random() < 0.2:  # 20% probability to change the direction of move
            # Choose a new direction randomly from the available options
            new_direction = random.choice(['up', 'down', 'left', 'right'])
            print(f"Agent {agent_number} intended to move {direction}, but moved {new_direction} instead.")
            direction = new_direction
      self.state.movement_update(agent_number, direction)



    def send_percept_to_agent(self, agent_number):
      p = self.state.get_percept_for_agent(agent_number)
      if(self.loc_observability==False):
        return {"dirty":p["dirty"]}
      if(self.dirt_observability==False):
        return {"loc":p["loc"]}
      self.state.make_room_dirty()